# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13vector_stream.proto"\x1f\n\x0fRequestResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\x32\x43\n\x0cVectorStream\x12\x33\n\x07\x61\x64\x64_one\x12\x10.RequestResponse\x1a\x10.RequestResponse"\x00(\x01\x30\x01\x62\x06proto3'
)


_REQUESTRESPONSE = DESCRIPTOR.message_types_by_name["RequestResponse"]
RequestResponse = _reflection.GeneratedProtocolMessageType(
    "RequestResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _REQUESTRESPONSE,
        "__module__": "vector_stream_pb2"
        # @@protoc_insertion_point(class_scope:RequestResponse)
    },
)
_sym_db.RegisterMessage(RequestResponse)

_VECTORSTREAM = DESCRIPTOR.services_by_name["VectorStream"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _REQUESTRESPONSE._serialized_start = 23
    _REQUESTRESPONSE._serialized_end = 54
    _VECTORSTREAM._serialized_start = 56
    _VECTORSTREAM._serialized_end = 123
# @@protoc_insertion_point(module_scope)
