# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vector_stream_pb2 as vector__stream__pb2


class VectorStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_one = channel.stream_stream(
            "/VectorStream/add_one",
            request_serializer=vector__stream__pb2.RequestResponse.SerializeToString,
            response_deserializer=vector__stream__pb2.RequestResponse.FromString,
        )


class VectorStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_one(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VectorStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "add_one": grpc.stream_stream_rpc_method_handler(
            servicer.add_one,
            request_deserializer=vector__stream__pb2.RequestResponse.FromString,
            response_serializer=vector__stream__pb2.RequestResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "VectorStream", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class VectorStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_one(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/VectorStream/add_one",
            vector__stream__pb2.RequestResponse.SerializeToString,
            vector__stream__pb2.RequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
